# Configuración para el User Management Service
server.port=8083

# Lee la clave secreta desde una variable de entorno llamada JWT_SECRET
app.jwt.secret=a15dea675ba90b62b6f0c12f4ee3c8b42e3568bbbf71e18f7687da318ec8e6fa79551d9778e993a4488f9d2a0baee224cdd433377d98106e41ab44365683e18d


# Tiempo de expiración del token (86400000 = 1 día)
app.jwt.expiration-ms=86400000

# Conexión a Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

# Forzar hostname manualmente
spring.cloud.client.hostname=localhost

# Evitar que use la IP detectada automáticamente
eureka.instance.prefer-ip-address=false

# Forzar hostname manualmente (IMPORTANTE)
eureka.instance.hostname=localhost

# Conexión a la Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/users_db?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=update


